# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================

staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org
    - chain-name: arc-testnet
      url: https://arc-testnet.drpc.org

production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org
    - chain-name: arc-testnet
      url: https://arc-testnet.drpc.org
