# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================

local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org
    - chain-name: arc-testnet
      url: https://rpc.testnet.arc.network

staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org
    - chain-name: arc-testnet
      url: https://rpc.testnet.arc.network

production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org
    - chain-name: arc-testnet
      url: https://rpc.testnet.arc.network
