[profile.default]
bytecode_hash = "none"
evm_version = "cancun"
ffi = true
fs_permissions = [{ access = "read-write", path = "./deployments" }]
libs = ["lib"]
out = "out"
optimizer = true
optimizer_runs = 1
solc_version = "0.8.34"
src = "src"
via_ir = true

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536
